### ISSUE TITLE
微信小程序中没反应

### ISSUE THREAD

**Issue by wen403** [uni-helper/axios-adapter#18]
### 描述问题

# 微信小程序中没反应也没报错很奇怪
# 在h5中他是正常运行的
![image](https://github.com/uni-helper/axios-adapter/assets/67454874/bed2a7eb-fe4a-4a62-ba23-d4e200920c6e)
![image](https://github.com/uni-helper/axios-adapter/assets/67454874/4ab98119-609f-4564-8246-a6457110a882)

### 复现

https://github.com/uni-helper/axios-adapter/assets/67454874/015792c9-992b-4e17-8429-7857204dd3f1

![image](https://github.com/uni-helper/axios-adapter/assets/67454874/2b9d64f3-54b5-41d8-bcb1-932c5f1d604c)

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
    Memory: 4.52 GB / 15.92 GB
  Binaries:
    Node: 16.13.0 - D:\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\pnpm\yarn.CMD
    npm: 8.1.0 - D:\nodejs\npm.CMD
    pnpm: 8.0.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.188)
    Internet Explorer: 11.0.19041.1566
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
你好，未能复现
