### ISSUE TITLE
小程序下不支持 AbortController ，一般怎么处理？

### ISSUE THREAD

**Issue by tlerbao** [uni-helper/axios-adapter#32]
### 描述问题

小程序下不支持 AbortController ，一般怎么处理？

### 复现

<img width="870" alt="CleanShot 2024-05-21 at 09 19 42@2x" src="https://github.com/uni-helper/axios-adapter/assets/20442232/b0bcc7a3-0b41-41c8-b57c-2342fffb9908">

### 系统信息

基础环境信息:
  - os: `macOS 13.3`
  - node: `18.19.0`
  - vscode: `1.89.1`
  - volar: `2.0.19`

基础依赖信息:
  - vue: `3.4.26`
  - vite: `5.2.8`
  - @dcloudio/uni-app: `3.0.0-4010420240430001`

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
https://axios-http.com/docs/cancellation

虽然没测试，但是直接用 CancelToken 应该也是可以的！
